#! /bin/sh

bspc config border_width        3
bspc config window_gap          35
bspc config top_padding         16
bspc config focus_follows_pointer true

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor DFP6 -d I II III IV V # Centre
bspc monitor DFP7 -d VI VII VIII IX X # Centre

