#! /bin/sh

bspc config border_width        3       # Size of the window border
bspc config window_gap          40      # Margin around each window
bspc config top_padding         16      # Extra margin at top for panel
bspc config focus_follows_pointer true  # Make mouse position trigger window focur

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor DFP6 -d I II III IV V      # Monitor workspace definition
bspc monitor DFP7 -d VI VII VIII IX X   # Monitor workspace definition

panel &                                 # Start the panel

